### ISSUE TITLE
Ampersand in Bookmap title  not output in footers

### ISSUE THREAD

**Issue by etudsbery** [leximation/docs-ditafmx-2#3]
(dita-fmx 1.1.15)
I have a bookmap title with an ampersand in the title. When I run the "Generate book from map" command, I end up with &amp; in the footer. I have tried escaping with &amp; (ampersand amp semi-colon) in the title but this doesn't work either.

**Comment by leximation** [comment]
This sounds like a possible bug in DITA-FMx. This GitHub repo and associated Issues tracker is for the documentation. Please report software bugs to the Yahoo dita-fmx-users group or send directly in to Leximation. Also, DITA-FMx 1.1.15 is more than 3 years old, the current release is 2.0.04. I'll test this in the current release, and if it's still a problem will fix. Thanks.
